### user api 


# create user api endpoint
###
GET http://localhost:8000/api/v1/users


###register user
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
 "name":"nisha",
 "email":"nisha123@gmail.com",
 "password": "12345"
}

### login user
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
 
 "email":"nisha123@gmail.com",
 "password": "12345"
}

###task api

### get task

GET http://localhost:8000/api/v1/task


###
POST http://localhost:8000/api/v1/task
Content-Type: application/json
Authorization: 62b19aba45c4f3a9de279ed7

{
    
    "task":"cycling",
    "hr":25
}


### delete 
DELETE http://localhost:8000/api/v1/task